import type { KnowledgeComponent } from "@/types/knowledge";

/**
 * Bundled fallback so the palette works before the API responds or when the device is
 * offline with a cold cache. It intentionally mirrors only core primitives; the full
 * library comes from `GET /api/v1/knowledge/components`.
 */
export const FALLBACK_COMPONENTS: KnowledgeComponent[] = [
  {
    type: "load_balancer",
    name: "Load Balancer",
    category: "networking",
    purpose: ["traffic distribution", "health checks"],
    characteristics: { throughput: "high", availability: "high" },
    tradeoffs: ["extra network hop"],
    alternatives: ["API gateway"],
    commonPatterns: ["round robin", "active health checks"],
    antiPatterns: ["multiple app instances with no load balancing layer"],
  },
  {
    type: "cdn",
    name: "CDN",
    category: "networking",
    purpose: ["static asset delivery", "edge caching"],
    characteristics: { latency: "low", scope: "global edge" },
    tradeoffs: ["cache invalidation cost"],
    alternatives: ["object storage + CDN"],
    commonPatterns: ["immutable asset hashing"],
    antiPatterns: ["serving all traffic through a single origin region"],
  },
  {
    type: "api_service",
    name: "API Service",
    category: "compute",
    purpose: ["request handling", "business logic"],
    characteristics: { latency: "low", scaling: "horizontal" },
    tradeoffs: ["stateful instances limit horizontal scaling"],
    alternatives: ["serverless functions"],
    commonPatterns: ["stateless request handling"],
    antiPatterns: ["holding sessions in instance memory with multiple replicas"],
  },
  {
    type: "worker",
    name: "Worker",
    category: "compute",
    purpose: ["background jobs", "async processing"],
    characteristics: { execution: "async", scaling: "queue depth driven" },
    tradeoffs: ["at-least-once delivery semantics"],
    alternatives: ["serverless functions"],
    commonPatterns: ["queue consumer"],
    antiPatterns: ["long-running work inside synchronous request paths"],
  },
  {
    type: "postgresql",
    name: "PostgreSQL",
    category: "storage",
    purpose: ["transactional relational data", "strong consistency"],
    characteristics: { consistency: "strong", durability: "high" },
    tradeoffs: ["primary node scales vertically first"],
    alternatives: ["MySQL"],
    commonPatterns: ["primary plus read replicas"],
    antiPatterns: ["one unindexed hot table"],
  },
  {
    type: "redis",
    name: "Redis",
    category: "storage",
    purpose: ["caching", "sessions", "rate limiting"],
    characteristics: { latency: "very_low", durability: "not a primary store" },
    tradeoffs: ["memory cost", "cache invalidation complexity"],
    alternatives: ["Memcached"],
    commonPatterns: ["cache-aside", "TTL-based expiry"],
    antiPatterns: ["treating the cache as the source of truth"],
  },
  {
    type: "object_storage",
    name: "Object Storage",
    category: "storage",
    purpose: ["blob storage", "static assets", "backups"],
    characteristics: { durability: "high", access: "HTTP API" },
    tradeoffs: ["egress pricing"],
    alternatives: ["S3-compatible providers"],
    commonPatterns: ["pre-signed upload URLs"],
    antiPatterns: ["streaming large media through application servers"],
  },
  {
    type: "kafka",
    name: "Kafka",
    category: "messaging",
    purpose: ["event streaming", "durable event log"],
    characteristics: { delivery: "ordered per partition", retention: "durable log" },
    tradeoffs: ["operational complexity", "consumer lag monitoring"],
    alternatives: ["RabbitMQ", "managed queues"],
    commonPatterns: ["publish-subscribe", "consumer groups"],
    antiPatterns: ["event stream with no visible consumer"],
  },
  {
    type: "authentication",
    name: "Authentication",
    category: "services",
    purpose: ["identity verification", "session issuance"],
    characteristics: { criticality: "high", integration: "external identity provider" },
    tradeoffs: ["external dependency"],
    alternatives: ["managed auth services"],
    commonPatterns: ["OAuth/OIDC"],
    antiPatterns: ["custom password storage without expertise"],
  },
  {
    type: "logging",
    name: "Logging",
    category: "observability",
    purpose: ["structured logs", "debugging"],
    characteristics: { format: "structured JSON preferred" },
    tradeoffs: ["storage cost"],
    alternatives: ["managed log services"],
    commonPatterns: ["correlation IDs", "log levels"],
    antiPatterns: ["logging secrets, tokens, or full user payloads"],
  },
  {
    type: "secrets_manager",
    name: "Secrets Manager",
    category: "security",
    purpose: ["secret storage", "rotation"],
    characteristics: { access: "audited", rotation: "supported" },
    tradeoffs: ["runtime dependency on the secrets backend"],
    alternatives: ["platform-provided secret stores"],
    commonPatterns: ["short-lived credentials"],
    antiPatterns: ["secrets committed to git or baked into images"],
  },
];
